version: '2'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - PORT=3000
      - RAILS_ENV=development
      - RACK_ENV=development
    volumes:
      - "./:/usr/src/i2i"
    ports:
      - 3001:3000
    links:
      - db
    depends_on:
      - db
